/* AUTO-GENERATED by scripts/build-certificates.js — do not edit by hand.
   Re-run `node scripts/build-certificates.js` after changing /Certificates. */
window.CERTIFICATES = [
  {
    "file": "Certificate - Construction Fundamentals.png",
    "pdfFile": "Certificate - Construction Fundamentals.pdf",
    "title": "Construction Fundamentals",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785012891385,
    "size": "1.3 MB"
  },
  {
    "file": "Certificate - WHMIS (2025).png",
    "pdfFile": "Certificate - WHMIS (2025).pdf",
    "title": "WHMIS (2025)",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011202889,
    "size": "851 KB"
  },
  {
    "file": "Certificate - Preventing Harassment and Violence in the Workplace for Employees.png",
    "pdfFile": "Certificate - Preventing Harassment and Violence in the Workplace for Employees.pdf",
    "title": "Preventing Harassment and Violence in the Workplace for Employees",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011202655,
    "size": "852 KB"
  },
  {
    "file": "Certificate - Introduction to Gender-Based Analysis Plus.png",
    "pdfFile": "Certificate - Introduction to Gender-Based Analysis Plus.pdf",
    "title": "Introduction to Gender-Based Analysis Plus",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011202387,
    "size": "245 KB"
  },
  {
    "file": "Certificate - Discover Cyber Security.png",
    "pdfFile": "Certificate - Discover Cyber Security.pdf",
    "title": "Discover Cyber Security",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011202156,
    "size": "844 KB"
  },
  {
    "file": "Certificate - Certificate of Service.png",
    "pdfFile": "Certificate - Certificate of Service.pdf",
    "title": "Certificate of Service",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011201925,
    "size": "24.0 MB"
  },
  {
    "file": "Certificate - Certificate of Enrolment.png",
    "pdfFile": "Certificate - Certificate of Enrolment.pdf",
    "title": "Certificate of Enrolment",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011201644,
    "size": "22.2 MB"
  },
  {
    "file": "Certificate - WHMIS 2015 (2022).png",
    "pdfFile": "Certificate - WHMIS 2015 (2022).pdf",
    "title": "WHMIS 2015 (2022)",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011201385,
    "size": "128 KB"
  },
  {
    "file": "Certificate - Safety Orienation.png",
    "pdfFile": "Certificate - Safety Orienation.pdf",
    "title": "Safety Orienation",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011201078,
    "size": "128 KB"
  },
  {
    "file": "Certificate - Safe Driving Course Mod 10.png",
    "pdfFile": "Certificate - Safe Driving Course Mod 10.pdf",
    "title": "Safe Driving Course Mod 10",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011200995,
    "size": "473 KB"
  },
  {
    "file": "Certificate - Safe Driving Course Final Exam.png",
    "pdfFile": "Certificate - Safe Driving Course Final Exam.pdf",
    "title": "Safe Driving Course Final Exam",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011200758,
    "size": "477 KB"
  },
  {
    "file": "Certificate - RCAF IBTS Law Of Armed Conflict IS3.png",
    "pdfFile": "Certificate - RCAF IBTS Law Of Armed Conflict IS3.pdf",
    "title": "RCAF IBTS Law Of Armed Conflict IS3",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011200527,
    "size": "476 KB"
  },
  {
    "file": "Certificate - RCAF IBTS Apply Explosive Threat And Hazard Awaresness And Recognition IS1.png",
    "pdfFile": "Certificate - RCAF IBTS Apply Explosive Threat And Hazard Awaresness And Recognition IS1.pdf",
    "title": "RCAF IBTS Apply Explosive Threat And Hazard Awaresness And Recognition IS1",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011200295,
    "size": "485 KB"
  },
  {
    "file": "Certificate - RCAF IBST Negotiate And Investigate IS.png",
    "pdfFile": "Certificate - RCAF IBST Negotiate And Investigate Is.pdf",
    "title": "RCAF IBST Negotiate And Investigate IS",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011200057,
    "size": "475 KB"
  },
  {
    "file": "Certificate - RCAF IBST Information Security IS2.png",
    "pdfFile": "Certificate - RCAF IBST Information Security IS2 .pdf",
    "title": "RCAF IBST Information Security IS2",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011199832,
    "size": "472 KB"
  },
  {
    "file": "Certificate - Public Key Infrastructure.png",
    "pdfFile": "Certificate - Public Key Infrastructure.pdf",
    "title": "Public Key Infrastructure",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011199549,
    "size": "476 KB"
  },
  {
    "file": "Certificate - Introduction to Indigenous Cultures.png",
    "pdfFile": "Certificate - Introduction to Indigenous Cultures.pdf",
    "title": "Introduction to Indigenous Cultures",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011199310,
    "size": "476 KB"
  },
  {
    "file": "Certificate - General Safety Individual Course.png",
    "pdfFile": "Certificate - General Safety Individual Course.pdf",
    "title": "General Safety Individual Course",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011198769,
    "size": "475 KB"
  },
  {
    "file": "Certificate - DND CAF Information Management.png",
    "pdfFile": "Certificate - DND CAF Information Management.pdf",
    "title": "DND CAF Information Management",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011198494,
    "size": "475 KB"
  },
  {
    "file": "Certificate - Canadian Armed Forces 101 for Civilians.png",
    "pdfFile": "Certificate - Canadian Armed Forces 101 for Civilians.pdf",
    "title": "Canadian Armed Forces 101 for Civilians",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011198239,
    "size": "476 KB"
  },
  {
    "file": "Certificate - Canadian Armed Forces Safe Driving Course.png",
    "pdfFile": "Certificate - Canadian Armed Forces Safe Driving Course.pdf",
    "title": "Canadian Armed Forces Safe Driving Course",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011198001,
    "size": "479 KB"
  },
  {
    "file": "Certificate - Beginner Positive Space Awareness Micro-Credential.png",
    "pdfFile": "Certificate - Beginner Positive Space Awareness Micro-Credential.pdf",
    "title": "Beginner Positive Space Awareness Micro-Credential",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011197769,
    "size": "480 KB"
  },
  {
    "file": "Certificate - Access to Information and Privacy at DND.png",
    "pdfFile": "Certificate - Access to Information and Privacy at DND.pdf",
    "title": "Access to Information and Privacy at DND",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011197535,
    "size": "477 KB"
  },
  {
    "file": "Certificate - Academic Integrity 2025.png",
    "pdfFile": "Certificate - Academic Integrity 2025.pdf",
    "title": "Academic Integrity 2025",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 25, 2026",
    "mtimeMs": 1785011197204,
    "size": "123 KB"
  },
  {
    "file": "Certificate - WHMIS 2015 GHS (2026).png",
    "pdfFile": "Certificate - WHMIS 2015 GHS (2026).pdf",
    "title": "WHMIS 2015 GHS (2026)",
    "type": "PNG Image",
    "ext": ".png",
    "date": "Jul 24, 2026",
    "mtimeMs": 1784932012095,
    "size": "4.8 MB"
  }
];
