/* ==========================================================================
   Mason Clement — Portfolio
   ========================================================================== */

document.addEventListener('DOMContentLoaded', () => {
  initTheme();
  renderCertificates();
  initScrollReveal();
  initTimeline();
  initCarousel();
  initBioToggle();
  initFileModal();
  initInfoModal();
  document.getElementById('year').textContent = new Date().getFullYear();
});

/* ---------------------------------------------------------------------
   Theme toggle (light / dark) — persists via localStorage,
   falls back to the visitor's system preference on first visit.
--------------------------------------------------------------------- */
function initTheme() {
  const root = document.documentElement;
  const toggle = document.getElementById('theme-toggle');

  const stored = localStorage.getItem('mc-theme');
  const systemPrefersLight = window.matchMedia('(prefers-color-scheme: light)').matches;
  const initial = stored || (systemPrefersLight ? 'light' : 'dark');

  root.setAttribute('data-theme', initial);
  toggle.setAttribute('aria-pressed', String(initial === 'light'));

  toggle.addEventListener('click', () => {
    const next = root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
    root.setAttribute('data-theme', next);
    toggle.setAttribute('aria-pressed', String(next === 'light'));
    localStorage.setItem('mc-theme', next);
  });
}

/* ---------------------------------------------------------------------
   Certificates — rendered from window.CERTIFICATES (certificates-data.js,
   generated by scripts/build-certificates.js from whatever is currently
   in /Certificates). The homepage carousel and the certificates.html
   explorer both read from this one list, so they can't drift apart.
--------------------------------------------------------------------- */
const DOC_ICON =
  '<svg class="{cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M6 2h9l3 3v17H6Z"/><path d="M15 2v3h3"/></svg>';
const IMAGE_ICON =
  '<svg class="{cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M6 2h9l3 3v17H6Z"/><path d="M15 2v3h3"/><circle cx="10.3" cy="12.3" r="1.2"/><path d="M8 18l2.4-2.8 1.8 2 2.6-3.4L18 18"/></svg>';

function isImageType(ext) {
  return ext === '.jpg' || ext === '.jpeg' || ext === '.png';
}

function certIcon(item, cls) {
  const markup = isImageType(item.ext) ? IMAGE_ICON : DOC_ICON;
  return markup.replace('{cls}', cls);
}

function certHref(item) {
  return `./Certificates/${item.file}`;
}

function certPdfHref(item) {
  return item.pdfFile ? `./Certificates/${item.pdfFile}` : '';
}

function renderCertificates() {
  if (!Array.isArray(window.CERTIFICATES)) return;
  const items = window.CERTIFICATES;

  renderCarousel(items.slice(0, 10));
  renderExplorer(items);
}

function renderCarousel(items) {
  const track = document.getElementById('carousel-track');
  if (!track || !items.length) return;

  track.innerHTML = items
    .map(
      (item) => `
    <a class="cert-card glass shine" href="${certHref(item)}"
       data-preview-src="${certHref(item)}"
       data-preview-type="${isImageType(item.ext) ? 'image' : 'pdf'}"
       data-preview-pdf="${certPdfHref(item)}"
       data-preview-name="${item.pdfFile || ''}">
      <div class="cert-thumb">${certIcon(item, '')}</div>
      <h3 class="cert-title">${item.title}</h3>
      <p class="cert-org">${item.type} · ${item.date}</p>
    </a>`
    )
    .join('');
}

function renderExplorer(items) {
  const table = document.querySelector('.explorer-table');
  const count = document.getElementById('explorer-count');
  if (!table) return;

  const head = table.querySelector('.explorer-head');
  table.querySelectorAll('.explorer-row:not(.explorer-head)').forEach((row) => row.remove());

  const rowsHtml = items
    .map(
      (item) => `
    <a class="explorer-row" href="${certHref(item)}"
       data-preview-src="${certHref(item)}"
       data-preview-type="${isImageType(item.ext) ? 'image' : 'pdf'}"
       data-preview-pdf="${certPdfHref(item)}"
       data-preview-name="${item.pdfFile || ''}">
      <span class="col-name">${certIcon(item, 'file-icon')}${item.title}</span>
      <span class="col-date">${item.date}</span>
      <span class="col-type">${item.type}</span>
      <span class="col-size">${item.size}</span>
    </a>`
    )
    .join('');

  head.insertAdjacentHTML('afterend', rowsHtml);
  if (count) count.textContent = `${items.length} item${items.length === 1 ? '' : 's'}`;
}

/* ---------------------------------------------------------------------
   File preview modal — opens certificate/resume PDFs and images in a
   blurred overlay instead of sending people off to download them.
   Ctrl/Cmd/middle-click still lets a link open normally in a new tab.
--------------------------------------------------------------------- */
function initFileModal() {
  const modal = document.getElementById('file-modal');
  if (!modal) return;
  const body = document.getElementById('file-modal-body');
  const download = document.getElementById('file-modal-download');

  function openModal(src, type, pdfHref, pdfName) {
    body.innerHTML =
      type === 'image'
        ? `<img src="${src}" alt="" />`
        : `<iframe src="${src}" title="Document preview"></iframe>`;

    if (download) {
      if (pdfHref) {
        download.href = pdfHref;
        download.setAttribute('download', pdfName || '');
        download.hidden = false;
      } else {
        download.hidden = true;
        download.removeAttribute('href');
      }
    }

    modal.classList.add('open');
    modal.setAttribute('aria-hidden', 'false');
    document.body.classList.add('modal-open');
  }

  function closeModal() {
    modal.classList.remove('open');
    modal.setAttribute('aria-hidden', 'true');
    document.body.classList.remove('modal-open');
    body.innerHTML = '';
  }

  modal.querySelectorAll('[data-modal-close]').forEach((el) => {
    el.addEventListener('click', closeModal);
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && modal.classList.contains('open')) closeModal();
  });

  document.addEventListener('click', (e) => {
    // let the download link's own click through instead of treating it
    // as a "reopen the modal" trigger
    if (e.target.closest('#file-modal-download')) return;

    const trigger = e.target.closest('[data-preview-src]');
    if (!trigger) return;
    if (e.ctrlKey || e.metaKey || e.shiftKey || e.button === 1) return;
    e.preventDefault();
    openModal(
      trigger.dataset.previewSrc,
      trigger.dataset.previewType,
      trigger.dataset.previewPdf,
      trigger.dataset.previewName
    );
  });
}

/* ---------------------------------------------------------------------
   Info modal — short blurred-box messages for the Resume dropdown's
   Cover Letter / Transcripts options (neither has a public file yet).
--------------------------------------------------------------------- */
const LOCK_ICON =
  '<path d="M6 11V8a6 6 0 0 1 12 0v3" /><rect x="4" y="11" width="16" height="10" rx="1.5" /><circle cx="12" cy="16" r="1.6" />';
const CONSTRUCTION_ICON =
  '<path d="M14.7 6.3a1 1 0 0 1 1.4 0l1.6 1.6a1 1 0 0 1 0 1.4l-8 8a1 1 0 0 1-.5.27l-3 .7a.5.5 0 0 1-.6-.6l.7-3a1 1 0 0 1 .27-.5l8-8Z" /><path d="M13 8l3 3" /><path d="M3 21h7" />';

function contactHref() {
  // index.html can jump straight to the section; every other page
  // (404, certificates, under-construction) has to route through it first.
  const onHomePage = /(^|\/)index\.html$/.test(window.location.pathname) ||
    window.location.pathname.endsWith('/');
  return onHomePage ? '#contact' : 'index.html#contact';
}

const INFO_MODAL_CONTENT = {
  transcripts: {
    icon: LOCK_ICON,
    title: 'Transcripts',
    text:
      "Transcripts are only available upon request and are not accessible by the public. Please contact me if you're an employer, and I'll be glad to send them your way.",
    linkText: 'Go to Contact →',
    linkHref: contactHref,
  },
  'cover-letter': {
    icon: CONSTRUCTION_ICON,
    title: 'Under Construction',
    text: 'This is currently being worked on. Come check back later for updates.',
  },
};

function initInfoModal() {
  const modal = document.getElementById('info-modal');
  if (!modal) return;
  const icon = document.getElementById('info-modal-icon');
  const title = document.getElementById('info-modal-title');
  const text = document.getElementById('info-modal-text');
  const link = document.getElementById('info-modal-link');

  function openModal(key) {
    const content = INFO_MODAL_CONTENT[key];
    if (!content) return;

    icon.innerHTML = content.icon;
    title.textContent = content.title;
    text.textContent = content.text;

    if (content.linkHref) {
      link.href = content.linkHref();
      link.textContent = content.linkText;
      link.hidden = false;
    } else {
      link.hidden = true;
      link.removeAttribute('href');
    }

    modal.classList.add('open');
    modal.setAttribute('aria-hidden', 'false');
    document.body.classList.add('modal-open');
  }

  function closeModal() {
    modal.classList.remove('open');
    modal.setAttribute('aria-hidden', 'true');
    document.body.classList.remove('modal-open');
  }

  modal.querySelectorAll('[data-modal-close]').forEach((el) => {
    el.addEventListener('click', closeModal);
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && modal.classList.contains('open')) closeModal();
  });

  document.addEventListener('click', (e) => {
    const trigger = e.target.closest('[data-info-modal]');
    if (!trigger) return;
    e.preventDefault();
    openModal(trigger.dataset.infoModal);
  });
}

/* ---------------------------------------------------------------------
   Scroll reveal — fades/slides sections in as they enter the viewport.
--------------------------------------------------------------------- */
function initScrollReveal() {
  const items = document.querySelectorAll('.reveal');
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('in-view');
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.1, rootMargin: '0px 0px -10% 0px' });

  items.forEach(item => observer.observe(item));
}

/* ---------------------------------------------------------------------
   Timeline — click/tap (or Enter/Space) to expand a milestone.
   Only one item open at a time keeps the section tidy.
--------------------------------------------------------------------- */
function initTimeline() {
  const items = document.querySelectorAll('.timeline-content');

  items.forEach(item => {
    item.addEventListener('click', () => {
      const isOpen = item.getAttribute('aria-expanded') === 'true';

      items.forEach(other => other.setAttribute('aria-expanded', 'false'));
      item.setAttribute('aria-expanded', String(!isOpen));
    });
  });
}

/* ---------------------------------------------------------------------
   About bio — collapsed by default with a "Read More" toggle.
--------------------------------------------------------------------- */
function initBioToggle() {
  const wrap = document.getElementById('bio-wrap');
  const btn = document.getElementById('bio-toggle');
  if (!wrap || !btn) return;

  const collapsedHeight = 220;
  wrap.style.maxHeight = collapsedHeight + 'px';

  btn.addEventListener('click', () => {
    const expanding = !wrap.classList.contains('expanded');

    if (expanding) {
      wrap.classList.add('expanded');
      wrap.style.maxHeight = wrap.scrollHeight + 'px';
      wrap.addEventListener('transitionend', function onEnd(e) {
        if (e.propertyName !== 'max-height') return;
        wrap.removeEventListener('transitionend', onEnd);
        if (wrap.classList.contains('expanded')) {
          wrap.style.maxHeight = 'none';
        }
      });
    } else {
      // pin the current (auto) height first so the shrink has a real
      // pixel value to transition from, then collapse on the next frame
      wrap.style.maxHeight = wrap.scrollHeight + 'px';
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          wrap.classList.remove('expanded');
          wrap.style.maxHeight = collapsedHeight + 'px';
        });
      });
    }

    btn.setAttribute('aria-expanded', String(expanding));
    btn.textContent = expanding ? 'Read Less' : 'Read More';
  });
}

/* ---------------------------------------------------------------------
   Certificate carousel — infinite loop (wraps from last back to first
   and vice versa), with buttons, dots, and swipe support.
--------------------------------------------------------------------- */
function initCarousel() {
  const track = document.getElementById('carousel-track');
  const dotsWrap = document.getElementById('carousel-dots');
  const prevBtn = document.querySelector('.carousel-btn.prev');
  const nextBtn = document.querySelector('.carousel-btn.next');
  if (!track || !dotsWrap || !prevBtn || !nextBtn) return;

  const cards = Array.from(track.children);
  if (!cards.length) return;

  let index = 0;
  let visibleCount = getVisibleCount();

  // Build dots
  cards.forEach((_, i) => {
    const dot = document.createElement('button');
    dot.setAttribute('aria-label', `Go to certificate ${i + 1}`);
    dot.addEventListener('click', () => goTo(i));
    dotsWrap.appendChild(dot);
  });
  const dots = Array.from(dotsWrap.children);

  function getVisibleCount() {
    const viewportWidth = track.parentElement.offsetWidth;
    const cardWidth = cards[0].getBoundingClientRect().width + 20; // + gap
    return Math.max(1, Math.floor(viewportWidth / cardWidth));
  }

  function update() {
    const cardWidth = cards[0].getBoundingClientRect().width + 20;
    track.style.transform = `translateX(-${index * cardWidth}px)`;
    dots.forEach((d, i) => d.classList.toggle('active', i === index));
  }

  function goTo(i) {
    const max = cards.length - 1;
    if (i > max) index = 0;          // wrap to first
    else if (i < 0) index = max;     // wrap to last
    else index = i;
    update();
  }

  prevBtn.addEventListener('click', () => goTo(index - 1));
  nextBtn.addEventListener('click', () => goTo(index + 1));

  // Swipe support
  let touchStartX = 0;
  track.addEventListener('touchstart', (e) => {
    touchStartX = e.touches[0].clientX;
  }, { passive: true });
  track.addEventListener('touchend', (e) => {
    const diff = e.changedTouches[0].clientX - touchStartX;
    if (diff > 40) goTo(index - 1);
    else if (diff < -40) goTo(index + 1);
  }, { passive: true });

  window.addEventListener('resize', () => {
    visibleCount = getVisibleCount();
    update();
  });

  update();
}
